// Generated by Grafana k6 Studio (1.4.0) on 2026-09-29T04:58:58.456Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";
import { Faker } from 'k6/x/faker';
import { vu } from 'k6/execution';

export const options = {
  stages: [
    { target: 10, duration: "30s" },
    { target: 10, duration: "30s" },
    { target: 2000, duration: "30s" },
    { target: 2000, duration: "2m30s" },
    { target: 0, duration: "1m" },
  ],
};

const faker = Faker();
const front_url = __ENV.FRONT_URL;
const back_url = __ENV.BACK_URL;
const VU_base = 10;

const VARS = {
  UserName: "0",
};

import { htmlReport } from 'https://raw.githubusercontent.com/benc-uk/k6-reporter/latest/dist/bundle.js';

export function handleSummary(data) {
  return {
    'report.html': htmlReport(data),
  };
}

type User = {
  user_name: string,
  password: string,
  email: string,
  token: string,
}

export function setup(): User[] {
  const results: User[] = [];
  let params;
  let resp;
  let url;

  for (let user_index = 0; user_index < VU_base; user_index++) {
    const user_name = faker.person.name() + faker.numbers.number(0, 2147483647);
    const password = faker.internet.password(true, false, true, true, false, 12);
    const email = `${user_name}@gmail.com`;

    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Linux"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
      tags: { name: "front GET /" },
    };

    url = http.url`${front_url}`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `POST`,
        "access-control-request-headers": `content-type`,
        origin: `${front_url}`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "options" },
    };

    url = http.url`${back_url}/api/v1/auth/register`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "POST /register" },
    };

    url = http.url`${back_url}/api/v1/auth/register`;
    resp = http.request(
      "POST",
      url,
      `{"name":"${user_name}","email":"${email}","password":"${password}"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
    var token = resp.json()["token"];

    const user = {
      user_name: user_name,
      password: password,
      email: email,
      token: token,
    }
    results.push(user);
  }

  return results;
}

export default function (users: User[]) {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
    const token = users[(vu.idInTest - 1) % users.length].token;

    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `GET`,
        "access-control-request-headers": `authorization`,
        origin: `${front_url}`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "options" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "GET /notes" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `POST`,
        "access-control-request-headers": `authorization,content-type`,
        origin: `${front_url}`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "options" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "POST /notes" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request(
      "POST",
      url,
      `{"title":"Title1Note","content":"Content1Note"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
    const note1Id = resp.json()["id"];

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "GET /notes" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "GET /notes" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "content-type": `application/json`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "POST /notes" },
    };

    url = http.url`${back_url}/api/v1/notes`;
    resp = http.request(
      "POST",
      url,
      `{"title":"TItle2Note","content":"Content2Note"}`,
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
    const note2Id = resp.json()["id"];

    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `DELETE`,
        "access-control-request-headers": `authorization`,
        origin: `${front_url}`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "options" },
    };

    url = http.url`${back_url}/api/v1/notes/${note1Id}`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "DELETE /notes" },
    };

    url = http.url`${back_url}/api/v1/notes/${note1Id}`;
    resp = http.request("DELETE", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `*/*`,
        "access-control-request-method": `DELETE`,
        "access-control-request-headers": `authorization`,
        origin: `${front_url}`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "options" },
    };

    url = http.url`${back_url}/api/v1/notes/${note2Id}`;
    resp = http.request("OPTIONS", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "sec-ch-ua-platform": `"Linux"`,
        authorization: `Bearer ${token}`,
        accept: `application/json`,
        "sec-ch-ua": `"Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"`,
        "sec-ch-ua-mobile": `?0`,
        origin: `${front_url}`,
        "sec-fetch-site": `cross-site`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `${front_url}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
      tags: { name: "DELETE /notes" },
    };

    url = http.url`${back_url}/api/v1/notes/${note2Id}`;
    resp = http.request("DELETE", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
